version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-149482-0.cloudclusters.net:19645/swd392?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=tG5XJX4x
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=tG5XJX4x
    ports:
      - "19645:19645"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
